package com.textvision.alistclient.admin.form

import com.textvision.alistclient.network.dto.ConfigItem

/**
 * 后端字段名 -> 中文显示名映射。覆盖 ConfigItem.name / SettingItem.key。
 * 后端返回的 label 多为英文（且不一定每条都有），统一忽略，改由本表覆盖。
 */
internal val labelOverrides: Map<String, String> = mapOf(
    "mount_path" to "挂载路径",
    "order" to "排序权重",
    "remark" to "备注",
    "cache_expiration" to "缓存过期(分钟)",
    "web_proxy" to "Web 代理",
    "webdav_policy" to "WebDAV 策略",
    "down_proxy_url" to "下载代理地址",
    "down_proxy_sign" to "下载代理签名密钥",
    "proxy_range" to "代理范围请求",
    "order_by" to "排序字段",
    "order_direction" to "排序方向",
    "extract_folder" to "解压文件夹",
    "disable_index" to "禁用索引",
    "enable_sign" to "启用签名",
    "extract_password" to "解压密码",
    "disable" to "禁用",
    // storage driver additional/common keys
    "root_folder_path" to "根目录路径",
    "thumbnail" to "启用缩略图",
    "thumbnail_strategy" to "缩略图策略",
    "thumb_cache_folder" to "缩略图缓存目录",
    "thumb_concurrency" to "缩略图并发数",
    "thumb_format" to "缩略图格式",
    "thumb_quality" to "缩略图质量",
    "use_ffmpeg" to "使用 ffmpeg",
    "ffmpeg_path" to "ffmpeg 路径",
    "token" to "令牌",
    "username" to "用户名",
    "password" to "密码",
    "url" to "地址",
    "path" to "路径",
    "endpoint" to "接入点",
    "bucket" to "存储桶",
    "region" to "地域",
    "access_key_id" to "AccessKey ID",
    "access_key_secret" to "AccessKey Secret",
    "session_token" to "Session Token",
    "storage_class" to "存储类型",
    "alist_token" to "Alist 令牌",
    "site_url" to "站点地址",
    "cdn_url" to "CDN 地址",
    "sign_url" to "签名 URL",
    "internal" to "内网访问",
    "container" to "容器名",
    "key_id" to "Key ID",
    "key_secret" to "Key Secret",
    "oaep" to "RSA OAEP",
    "private_key" to "私钥",
    "rapid" to "rapid 上传",
    "no_cache" to "禁用缓存",
    "no_upload" to "禁用上传",
    "no_download" to "禁用下载",
    "proxy" to "代理",
    "proxy_type" to "代理类型",
    "sftp_passphrase" to "SFTP 口令",
    "sftp_key" to "SFTP 私钥",
    "sftp_key_path" to "SFTP 私钥路径",
    "sftp_disable_concurrent" to "SFTP 禁用并发",
    "sftp_remove_root" to "SFTP 移除根目录",
    "ftp_passive" to "FTP 被动模式",
    "ftp_encoding" to "FTP 编码",
    "ssl" to "SSL",
    "tls" to "TLS",
    "skip_tls_verify" to "跳过 TLS 校验",
    "allow_insecure" to "允许不安全连接",
    "client_id" to "客户端 ID",
    "client_secret" to "客户端密钥",
    "redirect_uri" to "回调地址",
    "redirect_url" to "回调地址",
    "scope" to "权限范围",
    "authorize_url" to "授权地址",
    "token_url" to "令牌地址",
    "open_api_token_endpoint" to "Open API 令牌端点",
    "host" to "主机",
    "port" to "端口",
    "database" to "数据库",
    "table_prefix" to "表前缀",
    "ssl_mode" to "SSL 模式",
    "conn_string" to "连接字符串",
    "max_connections" to "最大连接数",
    "min_connections" to "最小连接数",
    "connection_max_lifetime" to "连接最长生命周期(秒)",
    "max_idle_conns" to "最大空闲连接数",
    "keep_alive" to "保持连接",
    "max_concurrency" to "最大并发数",
    "max_upload_size" to "最大上传体积",
    "max_download_size" to "最大下载体积",
    "chunk_size" to "分块大小",
    "part_size" to "分片大小",
    "thread_num" to "线程数",
    "worker_num" to "Worker 数",
    "parallel" to "并发数",
    "retry_count" to "重试次数",
    "timeout" to "超时(秒)",
    "user_agent" to "User-Agent",
    "referer" to "Referer",
    "origin" to "Origin",
    "download_api" to "下载 API",
    "upload_api" to "上传 API",
    "list_api" to "列表 API",
    "archive_path" to "归档路径",
    "hash_file_suffix" to "哈希文件后缀",
    "encrypt_password" to "加密密码",
    "encrypt_salt" to "加密盐",
    "encrypt_filename" to "加密文件名",
    "decrypted_text" to "解密文本",
    "metadata" to "元数据",
    "stream" to "流模式",
    "strict" to "严格模式",
    "overwrite" to "覆盖",
    "rename" to "重命名",
    "skip" to "跳过",
    "skip_exist" to "跳过已存在",
    "mkdir" to "自动创建目录",
    "move" to "移动",
    "copy" to "复制",
    "delete" to "删除",
    "delete_force" to "强制删除",
    "recycle" to "放入回收站",
    "dump_limit" to "回收上限",
    "cron" to "定时任务",
    "schedule_retry_count" to "定时重试次数",
    "schedule_interval" to "定时间隔(秒)",
    "share_password" to "分享密码",
    "share_expire" to "分享过期(秒)",
    "share_preview" to "分享预览",
    "index" to "索引",
    "index_progress" to "索引进度",
    "index_max_size" to "索引最大体积",
    "index_min_size" to "索引最小体积",
    "index_extensions" to "索引文件后缀",
    "max_index_files" to "最大索引文件数",
    "no_overwrite_upload" to "上传不覆盖",
    "use_s3_host" to "使用 S3 主机",
    "sign_url_expire" to "签名 URL 过期(秒)",
    "sign_url_prefix" to "签名 URL 前缀",
    "use_unsigned_payload" to "使用未签名 payload",
    "virtual_host" to "虚拟主机",
    "cdn_host" to "CDN 主机",
    "check_404" to "检查 404",
    "check_403" to "检查 403",
    "modify" to "保留修改时间",
    "encoding" to "编码",
    "encrypt_key" to "加密密钥",
    "encrypt_iv" to "加密 IV",
    "private_key_passphrase" to "私钥口令",
    "use_pcd_to_resolve_resource_id" to "使用 PCD 解析资源 ID",
    "drive_id" to "网盘 ID",
    "share_id" to "分享 ID",
    "share_pwd" to "分享密码",
    "share_token" to "分享令牌",
    "share_vcode" to "分享提取码",
    "share_vtype" to "分享类型",
    "share_url" to "分享链接",
    "rapid_upload" to "秒传",
    "upload_thread" to "上传线程数",
    "download_thread" to "下载线程数",
    "page_size" to "每页数量",
    "page_num" to "页码",
    "sort_field" to "排序字段",
    "sort_direction" to "排序方向",
    "list_object_key" to "列表字段名",
    "filter_dir" to "过滤目录",
    "filter_file" to "过滤文件",
    "filter_regex" to "过滤正则",
    "include_dir" to "包含目录",
    "include_file" to "包含文件",
    "include_regex" to "包含正则",
    "exclude_dir" to "排除目录",
    "exclude_file" to "排除文件",
    "exclude_regex" to "排除正则",
    "case_sensitive" to "区分大小写",
    "file_type" to "文件类型",
    "mime_type" to "MIME 类型",
    "content_type" to "Content-Type",
    "headers" to "请求头",
    "cookies" to "Cookie",
    "auth" to "鉴权",
    "auth_token" to "鉴权令牌",
    "bearer_token" to "Bearer Token",
    "access_token" to "Access Token",
    "refresh_token" to "Refresh Token",
    "id_token" to "ID Token",
    "api_key" to "API Key",
    "secret" to "密钥",
    "secret_id" to "SecretId",
    "security_token" to "Security Token",
    "tenant_id" to "租户 ID",
    "project_id" to "项目 ID",
    "subscription_id" to "订阅 ID",
    "resource_group_name" to "资源组名",
    "app_key" to "AppKey",
    "app_secret" to "AppSecret",
    "account" to "账号",
    "mail" to "邮箱",
    "mobile" to "手机号",
    "nickname" to "昵称",
    "device_id" to "设备 ID",
    "fingerprint" to "指纹",
    "captcha" to "验证码",
    "vcode" to "验证码",
    "verification" to "校验码",
    "two_factor_code" to "二步验证码",
    "root_path" to "根目录",
    "virtual_path" to "虚拟路径",
    "prefix" to "前缀",
    "suffix" to "后缀",
    "replace_to" to "替换为",
    "find_regex" to "查找正则",
    "custom_cdn" to "自定义 CDN",
    "custom_proxy" to "自定义代理",
    "file_rename" to "文件重命名",
    "file_replace" to "文件替换",
    "file_upload" to "文件上传",
    "file_download" to "文件下载",
    "file_copy" to "文件复制",
    "file_move" to "文件移动",
    "file_delete" to "文件删除",
    "file_search" to "文件搜索",
    "file_archive" to "文件归档",
    "file_extract" to "文件解压",
    "torrent_file" to "种子文件",
    "magnet" to "磁力链接",
    "info_hash" to "Info Hash",
    "tracker" to "Tracker",
    "seed_time" to "做种时间(分)",
    "seed_ratio" to "做种分享率",
    "download_path" to "下载目录",
    "temp_path" to "临时目录",
    "config_dir" to "配置目录",
    "data_dir" to "数据目录",
    "backup_dir" to "备份目录",
    "log_dir" to "日志目录",
    "log_level" to "日志级别",
    "cache_path" to "缓存目录",
    "cache_size" to "缓存大小",
    "disk_usage" to "磁盘占用",
    "disk_total" to "磁盘总量",
    "disk_free" to "磁盘剩余",
    "enable_log" to "启用日志",
    "enable_debug" to "启用调试",
    "enable_trace" to "启用链路追踪",
    "enable_metrics" to "启用指标",
    "enable_healthz" to "启用健康检查",
    "index_worker" to "索引 Worker",
    "index_ttl" to "索引 TTL",
    "max_age" to "最大缓存时间(秒)",
    "expire" to "过期(秒)",
    "expires_in" to "过期(秒)",
    "no_index" to "不索引",
    "no_list" to "不列目录",
    "no_get" to "不可下载",
    "no_put" to "不可上传",
    "no_copy" to "不可复制",
    "no_move" to "不可移动",
    "no_rename" to "不可重命名",
    "no_delete" to "不可删除",
    "no_share" to "不可分享",
    "no_search" to "不可搜索",
    "no_archive" to "不可归档",
    "no_extract" to "不可解压",
    "no_wget" to "不可 wget",
    "aria2_options" to "Aria2 选项",
    "aria2_args" to "Aria2 启动参数",
    "aria2_binary" to "Aria2 二进制",
    "aria2_config" to "Aria2 配置",
    "qbit_config" to "qBittorrent 配置",
    "transcoding_args" to "转码参数",
    "transcoding_cmd" to "转码命令",
    "transcoder" to "转码器",
    "video_format" to "视频格式",
    "audio_format" to "音频格式",
    "image_format" to "图片格式",
    "subtitle_format" to "字幕格式",
    "preview_format" to "预览格式",
    "preview_page" to "预览页",
    "preview_pages" to "预览总页数",
    "preview_resize" to "预览缩放",
    "preview_width" to "预览宽度",
    "preview_height" to "预览高度",
    "preview_max_size" to "预览最大体积",
    "preview_timeout" to "预览超时(秒)",
    "preview_concurrency" to "预览并发数",
    "preview_extensions" to "预览文件后缀",
    "preview_ignore_pattern" to "预览忽略规则",
    "office_preview_service" to "Office 预览服务",
    "office_preview_url" to "Office 预览地址",
    "pdf_preview_service" to "PDF 预览服务",
    "pdf_preview_url" to "PDF 预览地址",
    "ocr_api" to "OCR API",
    "ocr_url" to "OCR 地址",
    "ocr_key" to "OCR 密钥",
    "ocr_lang" to "OCR 语言",
    "watermark" to "水印",
    "watermark_text" to "水印文字",
    "watermark_image" to "水印图片",
    "watermark_position" to "水印位置",
    "watermark_opacity" to "水印透明度",
    "watermark_font" to "水印字体",
    "watermark_size" to "水印字号",
    "watermark_color" to "水印颜色",
    "watermark_padding" to "水印边距",
    "watermark_diagonal" to "对角水印",
    "watermark_density" to "水印密度",
    "watermark_keep" to "保留原图水印",
    "use_proxy_url" to "使用代理 URL",
    "native_proxy" to "原生代理",
    "must_proxy" to "强制代理",
    "force_proxy" to "强制代理",
    "disable_proxy" to "禁用代理",
    "webdav_proxy" to "WebDAV 代理",
    "redirect" to "重定向",
    "redirect_url" to "重定向地址",
    "cookie" to "Cookie",
    "root_folder_id" to "根目录 ID",
    "use_transcoding_address" to "使用转码地址",
    "only_list_video_file" to "仅列出视频文件",
    "sort_name" to "排序字段",
    "sort_type" to "排序类型",
    "order_direction" to "排序方向",
    // site settings
    "site_title" to "站点标题",
    "logo" to "Logo URL",
    "login_background" to "登录页背景图",
    "announcement" to "登录页公告",
    "favicon" to "站点图标",
    "pwa_small_icon" to "PWA 小图标",
    "pwa_medium_icon" to "PWA 中图标",
    "pwa_large_icon" to "PWA 大图标",
    "pwa_display" to "PWA 显示模式",
    "pwa_theme_color" to "PWA 主题色",
    "pwa_background_color" to "PWA 背景色",
    "thumbnail_size" to "缩略图大小",
    "thumbnail_width" to "缩略图宽度",
    "thumbnail_height" to "缩略图高度",
    "thumbnail_cache" to "缩略图缓存数量",
    "thumbnail_concurrency" to "缩略图并发数",
    "thumb_pixel" to "缩略图最大像素",
    "thumb_suffix" to "缩略图后缀",
    "video_thumb_percentage" to "视频缩略图百分比",
    "video_thumb_pos" to "视频缩略图位置",
    "video_thumb_max_seek_sec" to "视频缩略图最大跳转秒",
    "site_name" to "站点名称",
    "home_pinned_object" to "主页置顶项",
    "site_beian" to "备案号",
    "click_to_count" to "点击计数",
    "show_readme" to "在文件夹内显示 README",
    "hide_readme" to "在文件夹内隐藏 README",
    "show_announce" to "显示公告",
    "show_hide" to "显示隐藏文件",
    "show_folder_in_image" to "在图片中显示文件夹",
    "show_func_btns" to "显示功能按钮",
    "show_path_btns" to "显示路径按钮",
    "show_image_reload_btns" to "显示图片刷新按钮",
    "show_related_future_btns" to "显示相关推荐按钮",
    "audience_prohibited" to "对游客禁用",
    "default_locale" to "默认语言",
    "version" to "Alist 版本",
    "index_settings" to "索引设置",
    "viewer_floor" to "目录浏览最高层数",
    "task_enabled" to "启用任务队列",
    "task_threads" to "任务队列线程数",
    "task_retry_count" to "任务重试次数",
    "task_retry_interval" to "任务重试间隔(秒)",
    "aria2_enabled" to "启用 Aria2",
    "aria2_rpc_url" to "Aria2 RPC 地址",
    "aria2_rpc_secret" to "Aria2 RPC 密钥",
    "aria2_dirs" to "Aria2 下载目录",
    "aria2_options" to "Aria2 选项",
    "aria2_token" to "Aria2 令牌",
    "aria2_max_running_tasks_count" to "Aria2 最大任务数",
    "qbit_enabled" to "启用 qBittorrent",
    "qbit_url" to "qBittorrent 地址",
    "qbit_seedtime" to "qBittorrent 做种时间(分钟)",
    "transcoding_enabled" to "启用视频转码",
    "transcoding_cache" to "转码缓存目录",
    "transcoding_threads" to "转码线程数",
    "transcoding_info" to "ffmpeg 路径",
    "transcoding_ts_memory_op" to "转码内存优化",
    "auth_login_methods" to "登录方式",
    "enable_search" to "启用搜索",
    "search_enabled" to "启用搜索",
    "search_ignore_case" to "搜索忽略大小写",
    "search_max_recursion" to "搜索最大递归数",
    "search_file_suffix" to "搜索文件后缀",
    "ldap_login_enabled" to "启用 LDAP 登录",
    "ldap_login_url" to "LDAP 登录地址",
    "ldap_login_dn" to "LDAP DN",
    "ldap_login_pwd" to "LDAP 密码",
    "ldap_login_suffix" to "LDAP 后缀",
    "ldap_login_pattern" to "LDAP 用户名格式",
    "ldap_login_uid_pattern" to "LDAP UID 匹配",
    "ldap_login_uid_split" to "LDAP UID 分隔符",
    "ldap_login_base_dn" to "LDAP 基础 DN",
    "ldap_login_scope" to "LDAP 查询范围",
    "s3_preview" to "S3 预览",
    "forbidden" to "禁用的存储类型",
    "private_storage" to "私有存储",
    "mavis_search" to "是否使用 mavis 搜索",
    "google_search" to "Google 搜索",
    "index_progress" to "索引进度",
    "calculate_md5" to "计算 MD5",
    "ignore_file_download_backend" to "忽略直链后端",
    "storage_initialize" to "存储初始化",
    "delay" to "延迟",
    "load_on_page" to "分页加载",
    "auto_refresh_loaded_at_timeout" to "自动刷新超时(秒)",
    "client_redirect_preview_file" to "客户端重定向预览",
    "enable_archive_preview" to "启用压缩包预览",
    "archive_preview_max_size" to "压缩包预览最大体积",
    "archive_preview_timeout" to "压缩包预览超时(秒)",
    "archive_preview_concurrency" to "压缩包预览并发数",
    "always_overwrite" to "始终覆盖",
    "file_layered" to "文件夹置顶排序",
    "file_layered_probability" to "文件夹置顶概率",
    "user_agent_required" to "强制标识",
    "skip_check" to "跳过检查",
    "enable_cache" to "启用缓存",
    "enable_maven" to "启用 Maven",
    "read_buffer_size" to "读取缓冲(字节)",
    "write_buffer_size" to "写入缓冲(字节)",
    "max_read_concurrency" to "最大读取并发",
    "max_write_concurrency" to "最大写入并发",
    "enable_fingerprint" to "启用文件指纹",
    "fingerprint_hash_depth" to "指纹哈希深度",
    "fingerprint_count" to "指纹数量",
    "show_hidden" to "显示隐藏文件",
    "mkdir_perm" to "Mkdir 权限",
    "recycle_bin_path" to "回收站路径",
    "delete_permanently" to "永久删除",
    "expires_in" to "过期时间(秒)",
    "max_worker_num" to "最大 Worker 数",
    "max_worker_num_per_file" to "单文件最大 Worker 数",
    "cor_link_strict" to "校验 Cor 链接",
    "sign_all" to "对所有请求签名",
    "markdown_hide_char" to "Markdown 隐藏字符",
    "read_music_cover" to "读取音乐封面",
    "music_cover_from_metadata" to "从元数据读取音乐封面",
    "transcode_music" to "转码音乐",
    "music_transcode_format" to "音乐转码格式",
    "debug_path" to "调试路径",
    "single_drive" to "单存储模式",
    "mpegts_udp_size" to "MPEGTS UDP 包大小",
    "mpegts_subtitle_buf_size" to "MPEGTS 字幕缓冲大小",
    "disable_mp4_faststart" to "禁用 MP4 Faststart",
    "play_ignore_0_size" to "忽略 0 字节文件播放",
)

/** 后端字段名 -> 中文显示名。命中映射表返回中文，否则美化为可读英文（兜底）。 */
internal fun localizedLabel(name: String): String =
    labelOverrides[name] ?: name.replace("_", " ").replaceFirstChar { it.uppercase() }

sealed class FormItem {
    abstract val name: String
    abstract val label: String
    abstract val required: Boolean
    data class Text(
        override val name: String,
        override val label: String,
        override val required: Boolean = false,
    ) : FormItem()

    data class Url(
        override val name: String,
        override val label: String,
        override val required: Boolean = false,
    ) : FormItem()

    data class TextArea(
        override val name: String,
        override val label: String,
        override val required: Boolean = false,
    ) : FormItem()

    data class Bool(
        override val name: String,
        override val label: String,
        override val required: Boolean = false,
    ) : FormItem()

    data class Number(
        override val name: String,
        override val label: String,
        override val required: Boolean = false,
    ) : FormItem()

    data class Select(
        override val name: String,
        override val label: String,
        val options: List<Pair<String, String>>,
        override val required: Boolean = false,
    ) : FormItem()

    data class MultiSelect(
        override val name: String,
        override val label: String,
        val options: List<Pair<String, String>>,
        override val required: Boolean = false,
    ) : FormItem()

    companion object {
        fun fromConfigItem(item: ConfigItem): FormItem {
            val name = item.name
            // 后端返回的 label 多为英文，统一忽略并由我们这边的中文映射覆盖
            val label = localizedLabel(name)
            val required = item.required
            return when (item.type?.lowercase()) {
                "string" -> Text(name, label, required)
                "url" -> Url(name, label, required)
                "text" -> TextArea(name, label, required)
                "bool", "boolean" -> Bool(name, label, required)
                "number", "int", "integer", "float", "double" -> Number(name, label, required)
                "select" -> Select(name, label, parseOptions(item.options), required)
                "multi-select", "multi_select", "list", "strings" ->
                    MultiSelect(name, label, parseOptions(item.options), required)
                else -> Text(name, label, required) // 降级为 Text
            }
        }

        private fun parseOptions(raw: String?): List<Pair<String, String>> {
            if (raw.isNullOrBlank()) return emptyList()
            return raw.split(",").map { it.trim() }.filter { it.isNotEmpty() }
                .map { it to localizedLabel(it) }
        }
    }
}